apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-platform-lab
  labels:
    app: gcp-platform-lab
    tier: frontend
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-platform-lab
      tier: frontend
  template:
    metadata:
      labels:
        app: gcp-platform-lab
        tier: frontend
        env: dev
    spec:
      containers:
        - name: gcp-platform-lab
          image: europe-west1-docker.pkg.dev/sccoth-dev/gcp-lab-repo/gcp-platform-lab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name