apiVersion: v1
kind: Service
metadata:
  name: gcp-platform-lab-service
spec:
  type: LoadBalancer
  selector:
    app: gcp-platform-lab
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
